### ISSUE TITLE
AccumAnalyzer Couldn't Infer Reduction from Accumulation

### ISSUE THREAD

**Issue by kelayamatoz** [stanford-ppl/spatial#228]
In the attached app, the AccumAnalyzer could not infer reduction by just looking at line 164 ~ 168 and it's corresponding counter. As a result, the analyzer concludes that the initiation interval for the corresponding counter needs to be at least 2, whereas in theory II should be 1. 
[RNNMetaProgrammed_loop_perfection.scala.zip](https://github.com/stanford-ppl/spatial/files/3155106/RNNMetaProgrammed_loop_perfection.scala.zip)

**Comment by mattfel1** [comment]
Fixed by making it not split the accumulating register in memory analysis into two (accumulator and copy-read-by-someone-later-on).  I don't think it makes any sense to do this duplication if both are buffer size 1 (read in the same block), so I made it stop detecting that the accesses to the reg conflict in this case.
