### ISSUE TITLE
Implicit Casting

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#39]
This is probably related to our discussion with Stefan but I thought we decided we would put an extra input to arithmetic nodes that contains info about how to cast.  For now, I see this in the IR and I want to check if the jump to 32.32 bit without any explicit casting nodes is a mistake or not

```
                          x246 = FixAdd(b236,b242)
                           - Type: Fix[TRUE,_32,_0]
                          x247 = RegRead(x180)
                           - Type: Fix[TRUE,_32,_0]
                          x330 = FixFMA(x246,x247,b237)
                           - Type: Fix[TRUE,_32,_32]
                          x250 = FixMul(x330,Const(4: class emul.FixedPoint))
                           - Type: Fix[TRUE,_32,_0]
                          x251 = FixToFix(x250,TRUE,_64,_0)
                           - Type: Fix[TRUE,_64,_0]
```

**Comment by mattfel1** [comment]
Actually this causes some tricky issues that I don't think its safe to solve in cg, like in ReduceSimple muxing between different types:

```
              x66 = RegRead(x58)
               - Type: Fix[TRUE,_32,_0]
              x67 = FixMul(x66,b64)
               - Type: Fix[TRUE,_32,_0]
              x68 = RegRead(x61)
               - Type: Fix[TRUE,_32,_0]
              x98 = FixFMA(x66,b64,x68)
               - Type: Fix[TRUE,_32,_32]
              x71 = Mux(x69,x67,x98)
               - Type: Fix[TRUE,_32,_0]
```

**Comment by dkoeplin** [comment]
This wasn't intended behavior, it looks like it was caused by an bug with scalac inferring the implicit evidence for the integer and fraction bits when creating the FixFMA node. Proper behavior by scalac should have been either using _32 and _0 or giving an ambiguous implicits error.

Added a workaround for now. I'll have to be more careful about the way I pass implicits in the future until this bug is fixed.
