### ISSUE TITLE
GDA Unrolling Bug

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#40]
I made GDA with both folds parallelized by 2 and got the following controller tree:

https://www.dropbox.com/s/k3t035st58pj70u/controller_tree.html?dl=0

The inside fold is parallel 5482.  There seems to be an issue with the access indices to the accumulator BRAM (sigmaBlk) in pipe 5838 trying to use the counter values from pipe 5723 (4544 and 4545).

I attached the last IR.  
[0031_PrinterPlus.txt](https://github.com/stanford-ppl/spatial/files/517400/0031_PrinterPlus.txt)

**Comment by dkoeplin** [comment]
For posterity:

Issue was due to a combination of 2 things:
1. Lane-specific substitutions A -> B1 were leaking into the global substitution rules via allSubst, as substitution rules are always registered with this map, regardless of context.
2. Pre-transformation of the bound blocks in accum_fold saw the previous lane's substitution rules, causing the metadata to be transformed from A -> B1. Since there was no rule for B1 -> B2, only A -> B2, the metadata of the second lane carried references to the first lane's symbols.

Removed allSubst, since it was a failed experiment with global substitution records. Also have now changed ND addresses of rams to no longer be kept in metadata.
