### ISSUE TITLE
FIFO Banking Analysis Seems Broken Suddenly

### ISSUE THREAD

**Issue by mattfel1** [stanford-ppl/spatial#69]
For example:
```
CompactingFIFO.scala:46: Could not bank the following reads and writes for memory x140
[error]         out(i :: i + tileSize par 2) store fifo
```

Very likely that I did something that started causing this

**Comment by dkoeplin** [comment]
Traced this down to an issue where Alphas was actually empty as generated by the exhaustive banking methods. This was because we were taking the size of an iterator, which actually iterates through the collection, causing it to later appear empty. The logic using the size wasn't actually being used, so I just removed that part. App compiles now on broadcast branch.
