### ISSUE TITLE
par not speeding up

### ISSUE THREAD

**Issue by shadjis** [stanford-ppl/spatial#73]
[dp_simple.txt](https://github.com/stanford-ppl/spatial/files/2236424/dp_simple.txt)

attached app is simple dot product

unparallelized the dot product loop (ln 33) takes around 1024 cycles (w/ optimized reduce)
with par 4 loop takes 538
I think it should be more like 256
is this difference expected

**Comment by shadjis** [comment]
maybe I am doing something wrong because I pulled on issue61_cycle_detection and this went from 538 to 6403 cycles now?

**Comment by mattfel1** [comment]
Right. This is what I noticed too.  I just unbroke the optimizedReduce flag
on issue61 branch.  It turns out it was interacting badly with the IterDiff
stuff.  The 538 cycles vs 256 cycles is due to the FixAdd cycle.  This has
an II of 2 and I didn't put in the hack for FixAdd reductions (I only did
FixFMA reductions), so this would account for the slowdown of 2x.  Will see
if I can get accum branch wrapped up by tomorrow

**Comment by shadjis** [comment]
I pulled and I still get 6403, should it be 538 again now?

**Comment by mattfel1** [comment]
Oops, pull again

**Comment by mattfel1** [comment]
The loop takes 286 cycles on accum branch now

**Comment by mattfel1** [comment]
works on master and broadcast branches now
