### ISSUE TITLE
Hierarchical Banking - Bank Calculation Wrong

### ISSUE THREAD

**Issue by shadjis** [stanford-ppl/spatial#82]
App par_error_issue_82.scala gives different outputs when Reduce is parallelized with parallelizations 5, 5

**Comment by mattfel1** [comment]
Turns out that the case
```
Reduce(Reg[T](0.to[T]))(0 until 5 par 5, 0 until 5 par 5){ (i,j) => 
            mem(r+i,c+j)
}{_+_}
```
Computes banking schemes N=32, B=1, alpha=(1,5) but goes with hierarchical option of N=5, B=1 alpha=3 x N=5, B=1, alpha=3 for some reason. The banking calculation was just wrong for this sort of thing.  It was doing `banking.map(_.bankSelect(addr))` for bank calculation but in this case it would bankSelect twice on the 2D addr, so only the first index would be used both times

**Comment by mattfel1** [comment]
This should be good now
